# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  hootoutapi:
    image: hootoutapi
    build:
      context: .
      dockerfile: HootOutAPI/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081

  hootoutwebsockets:
    image: hoothutwebsockets
    build:
      context: .
      dockerfile: HootOutWebsockets/Dockerfile 
    ports:
      - 80:80
      - 81:81