services:
  hootoutapi:
    image: hootoutapi
    build:
      context: .
      dockerfile: HootOutAPI/Dockerfile
      args:
        - configuration=Debug
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - ${HOOTOUTAPI_HTTP_PORTS}:${HOOTOUTAPI_HTTP_PORTS}
      - ${HOOTOUTAPI_HTTPS_PORTS}:${HOOTOUTAPI_HTTPS_PORTS}
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: ${HOOTOUTAPI_HTTP_PORTS}
      #ASPNETCORE_HTTPS_PORTS: ${HOOTOUTAPI_HTTPS_PORTS}
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      RABBITMQ_HOST: ${RABBIT_HOSTNAME}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSOWRD}
      LOGS_FOLDER: /var/logs
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - logs:/var/logs

  hootoutwebsockets:
    image: hootoutwebsockets
    build:
      context: .
      dockerfile: HootOutWebsockets/Dockerfile
      args:
        - configuration=Debug
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - ${HOOTOUTWEBSOCKETS_HTTP_PORTS}:${HOOTOUTWEBSOCKETS_HTTP_PORTS}
      - ${HOOTOUTWEBSOCKETS_HTTPS_PORTS}:${HOOTOUTWEBSOCKETS_HTTPS_PORTS}
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: ${HOOTOUTWEBSOCKETS_HTTP_PORTS}
      #ASPNETCORE_HTTPS_PORTS: ${HOOTOUTWEBSOCKETS_HTTPS_PORTS}
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      RABBITMQ_HOST: ${RABBIT_HOSTNAME}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSOWRD}
      LOGS_FOLDER: /var/logs
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - logs:/var/logs

  postgres:
    image: postgres:18.6-trixie
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq: 
    image: rabbitmq:4.3.6-management
    restart: unless-stopped
    ports: 
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_HOST: ${RABBIT_HOSTNAME}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSOWRD}
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq

    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      retries: 3
      timeout: 5s
      interval: 30s

volumes:
  pgdata:
  logs:
  rabbitmq:
    driver: local