<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>424a8f47-620f-44c3-9a6a-0ec5df681998</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
    <PackageReference Include="NLog" Version="6.2.1" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\CommonDomain\CommonDomain.csproj" />
    <ProjectReference Include="..\Contracts\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\Domains\User\Users.csproj" />
    <ProjectReference Include="..\Infraestructure\Infraestructure\Infraestructure.csproj" />
    <ProjectReference Include="..\Integrations\PostgreSQL\PostgreSQL.csproj" />
  </ItemGroup>

</Project>
